name: neo4j_tableau_dart
description: A dart server to serve static website
version: 0.0.1
author: Casper CY Chiang <cychiang0823@gmail.com>
homepage: https://github.com/cychiang/neo4j-tableau
environment:
  sdk: ">=1.24.0 <2.0.0"
dependencies:
  shelf_static: "^0.2.7"